version: '3.9'
services:
  apache:
    image: ubuntu/apache2:2.4-22.04_edge
    ports:
      - 80
      - 443
    environment:
      - APACHE_LOG_DIR=/usr/local/apache2/log/
    volumes:
      - ./web:/var/www/html
      - ./conf:/usr/local/apache2/sites-enabled/
      - ./log:/usr/local/apache2/log/
    restart: always
